#!/usr/bin/env python3
"""Compile the ARM probe and turn it into something the interpreter can run.

The point of this step is that nothing about the test is hand-written machine
code. An ordinary C file is compiled by the ordinary toolchain, with
optimisation, for a processor this machine does not have - and what comes out
is whatever the compiler decided to emit. Those exact bytes are what the
interpreter is then asked to execute.

Two things come out: the code itself, as a flat block, and where each function
starts inside it, so the test can call them by name.
"""

import os
import subprocess
import sys


def build(clang, objcopy, nm, source, out_header):
    obj = out_header + ".o"
    binary = out_header + ".bin"

    subprocess.run(
        [clang, "--target=aarch64-unknown-none-elf", "-ffreestanding",
         "-fno-stack-protector", "-fno-pic", "-fno-pie", "-O2",
         "-c", source, "-o", obj],
        check=True,
    )

    # Just the instructions, with nothing around them.
    subprocess.run(
        [objcopy, "-O", "binary", "--only-section=.text", obj, binary],
        check=True,
    )

    with open(binary, "rb") as f:
        code = f.read()

    # Where each function begins.
    listing = subprocess.run([nm, "--defined-only", obj],
                             capture_output=True, text=True, check=True).stdout
    symbols = {}
    for line in listing.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[1] in ("t", "T"):
            symbols[parts[2]] = int(parts[0], 16)

    lines = []
    lines.append("/* Generated by tools/mkarmtest.py - do not edit by hand.")
    lines.append(" *")
    lines.append(" * Real AArch64 machine code, produced by the ordinary")
    lines.append(" * toolchain from tests/arm/probe.c with optimisation on.")
    lines.append(" * These are the bytes an ARM processor would be given. */")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#define ARM_PROBE_SIZE %d" % len(code))
    lines.append("")
    lines.append("static const uint8_t arm_probe_code[%d] = {" % len(code))
    for i in range(0, len(code), 12):
        chunk = ",".join("0x%02X" % b for b in code[i:i + 12])
        lines.append("    " + chunk + ",")
    lines.append("};")
    lines.append("")
    lines.append("/* Where each function starts, as an offset into the block. */")
    for name in sorted(symbols):
        lines.append("#define ARM_AT_%-12s %d" % (name, symbols[name]))
    lines.append("")

    with open(out_header, "w", newline="\n") as f:
        f.write("\n".join(lines))

    for temp in (obj, binary):
        try:
            os.remove(temp)
        except OSError:
            pass

    return len(code), len(symbols)


if __name__ == "__main__":
    if len(sys.argv) != 6:
        print("usage: mkarmtest.py <clang> <objcopy> <nm> <source> <header>")
        raise SystemExit(2)
    size, count = build(*sys.argv[1:])
    print("%d bytes of ARM code, %d functions" % (size, count))
