"""mkstick.py - a formatted FAT volume for the modelled USB stick.

The USB storage driver is exercised at the block level: sectors written and
read back.  That proves the transport and the SCSI commands, and it is where
usbmsc_model.c stops.

It does not prove the thing the user actually asked about.  "Nothing logs on
the USB stick" is a question about a FILESYSTEM on that stick - whether a
volume can be mounted from it, a file created, written and flushed all the way
down through the block layer to the device.  Every layer of that exists and
none of them had been run together on a USB device, because there is no USB
disk on any machine this is tested on.

So the modelled stick gets a real filesystem.  Built here by the same code that
formats the boot volume, rather than by anything in the kernel - a filesystem
this system created AND read back would only prove it agrees with itself.

Emitted as runs of non-zero bytes.  A freshly formatted volume is almost
entirely zeros: a boot sector, two copies of the allocation table and an empty
root directory, which is a couple of kilobytes out of a quarter of a megabyte.
Writing it out whole would be a megabyte of C source for no reason.

    python tools/mkstick.py [kernel/usbstick_image.h]
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))

import mkfat

# Matches MODEL_SECTORS * MODEL_SECTOR_SIZE in kernel/usbmsc_model.c.  A
# mismatch here is a volume whose own idea of its size disagrees with the
# device reporting it, which a filesystem driver is right to refuse.
SECTORS = 512
SECTOR = 512
SIZE = SECTORS * SECTOR


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        ROOT, "kernel", "usbstick_image.h")

    # Something already on it, so that mounting and reading are tested rather
    # than only mounting.  A file whose contents are known and not all one
    # value: a run of identical bytes reads back correctly from a driver that
    # has the offset wrong.
    marker = bytes((i * 37 + 11) & 0xFF for i in range(600))

    vol = mkfat.build_volume(SIZE, {"/KESTREL/STICK.CHK": marker},
                             label="KESTREL", fat_type=12)
    vol.ensure_dir("/logs")
    data = vol.to_bytes()

    if len(data) != SIZE:
        raise SystemExit("the volume came out %d bytes, not %d"
                         % (len(data), SIZE))

    # Non-zero runs, with a little tolerance for gaps so that two runs a few
    # bytes apart become one rather than two entries of overhead.
    runs = []
    i = 0
    while i < SIZE:
        if data[i] == 0:
            i += 1
            continue
        start = i
        gap = 0
        while i < SIZE and gap < 8:
            if data[i]:
                gap = 0
            else:
                gap += 1
            i += 1
        end = i - gap
        runs.append((start, data[start:end]))

    total = sum(len(r[1]) for r in runs)

    lines = []
    lines.append("/* Generated by tools/mkstick.py - do not edit by hand.")
    lines.append(" *")
    lines.append(" * A FAT12 volume of %d bytes, as the runs of it that are not"
                 % SIZE)
    lines.append(" * zero: %d bytes in %d run(s).  The modelled USB stick is"
                 % (total, len(runs)))
    lines.append(" * filled with this so that a filesystem can be mounted from")
    lines.append(" * it, which is what \"nothing logs on the stick\" is really")
    lines.append(" * a question about.")
    lines.append(" *")
    lines.append(" * Formatted by tools/mkfat.py - the same code that formats")
    lines.append(" * the boot volume, and NOT by anything in the kernel: a")
    lines.append(" * filesystem this system both created and read back would")
    lines.append(" * only prove it agrees with itself. */")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#define USBSTICK_BYTES %d" % SIZE)
    lines.append("#define USBSTICK_RUNS  %d" % len(runs))
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint32_t at;")
    lines.append("    uint32_t len;")
    lines.append("    const uint8_t *bytes;")
    lines.append("} usbstick_run_t;")
    lines.append("")

    for n, (at, blob) in enumerate(runs):
        lines.append("static const uint8_t usbstick_run%d[%d] = {" % (n, len(blob)))
        for j in range(0, len(blob), 16):
            chunk = blob[j:j + 16]
            lines.append("    " + ",".join("0x%02X" % b for b in chunk) + ",")
        lines.append("};")

    lines.append("")
    lines.append("static const usbstick_run_t usbstick_image[USBSTICK_RUNS] = {")
    for n, (at, blob) in enumerate(runs):
        lines.append("    { %d, %d, usbstick_run%d }," % (at, len(blob), n))
    lines.append("};")
    lines.append("")

    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print("-> %s (%d bytes of volume in %d run(s), %d bytes of source)"
          % (os.path.relpath(out, ROOT), total, len(runs),
             os.path.getsize(out)))


if __name__ == "__main__":
    main()
